apiVersion: v1
kind: ReplicationController
metadata:
  name: dropwizard-application
  labels:
    app: dropwizard-application
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dropwizard-application
    spec:
      containers:
      - name: dropwizard-application
        image: michaellee/dropwizard-guice-example
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USERNAME
          value: test
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: "default"
spec:
  ports:
  - name: "mysql"
    port: 3306
  selector:
    app: mysql
---
kind: Service
apiVersion: v1
metadata: 
  name: my-service
spec:
  selector:
    app: dropwizard-application
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
#type: LoadBalancer
